version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: store
      MYSQL_USER: store_user
      MYSQL_PASSWORD: store_pass
    volumes:
      - db-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./mock_data.sql:/docker-entrypoint-initdb.d/mock_data.sql:ro
    ports:
      - "3306:3306"
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: store_user
      DB_PASS: store_pass
      DB_NAME: store
      JWT_SECRET: secret
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  db-data:

